image: node:16

stages:
  - lint-test
  - deploy

Lint:
  stage: lint-test
  cache:
    key:
      files:
        - yarn.lock
      prefix: $CI_JOB_NAME
    paths:
      - node_modules/
      - .yarn/
  before_script:
    - yarn config set cache-folder $PWD/.yarn
    - yarn install --frozen-lockfile
  script:
    - yarn lint

# Test:
#   stage: lint-test
#   image: mcr.microsoft.com/playwright:focal
#   cache:
#     key:
#       files:
#         - yarn.lock
#       prefix: $CI_JOB_NAME
#     paths:
#       - node_modules/
#       - .yarn/
#       - .browsers/
#   before_script:
#     - yarn config set cache-folder $PWD/.yarn
#     - yarn install --frozen-lockfile
#     - yarn test-playwright-install
#   script:
#     - yarn test

Storybook:
  stage: deploy
  cache:
    key:
      files:
        - yarn.lock
      prefix: Lint
    paths:
      - node_modules/
      - .yarn/
    policy: pull
  before_script:
    - yarn config set cache-folder $PWD/.yarn
    - yarn install --frozen-lockfile
  script:
    - yarn build-storybook
    - git config --global user.email ci@sinch.com
    - git config --global user.name Bot
    - git checkout main
    - git reset
    - git add -f public
    - git commit -m "deploy storybok"
    - git push "https://gitlab-ci-token:$PROJECT_ACCESS_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git"
  artifacts:
    name: storybook
    paths:
      - public
