variables:
  GIT_DEPTH: 1

include:
  - project: "sinch/sinch-projects/sinch-platform/infra/pipeline/security"
    ref: v1-latest
    file: "auto_security.yml"

default:
  tags:
    - saas
    - application

stages:
  - lint
  - test
  - build
  - security-scan-third-parties
  - security-scan-consolidation
  - security-scan-sonar
  - deploy

lint:
  image: node:20
  stage: lint
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  cache:
    key:
      files:
        - pnpm-lock.yaml
      prefix: cache
    paths:
      - .pnpm-store
  variables:
    GIT_LFS_SKIP_SMUDGE: 1
  before_script:
    - ./scripts/ci-install-packages.sh
  script:
    - pnpm lint

visual-tests:
  stage: test
  image: mcr.microsoft.com/playwright:v1.33.0
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  cache:
    key:
      files:
        - pnpm-lock.yaml
      prefix: cache
    paths:
      - .pnpm-store
    policy: pull
  parallel:
    matrix:
      - BROWSER_FRAMEWORK:
          - chromium-react
          - firefox-vue
          - webkit-angular
  before_script:
    - - ./scripts/ci-install-packages.sh
  script:
    - pnpm --dir tests test:ci-$BROWSER_FRAMEWORK
  artifacts:
    when: on_failure
    paths:
      - tests/test-results

publish-components:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_TAG =~ /^components@/
  image: node:20
  cache:
    key:
      files:
        - pnpm-lock.yaml
      prefix: cache
    paths:
      - .pnpm-store
    policy: pull
  variables:
    GIT_LFS_SKIP_SMUDGE: 1
  before_script:
    - ./scripts/ci-install-packages.sh
  script:
    - ./scripts/publish-package.sh components ${NPM_TOKEN} $CI_COMMIT_TAG

publish-assets:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_TAG =~ /^assets@/
  image: node:20
  cache:
    key:
      files:
        - pnpm-lock.yaml
      prefix: cache
    paths:
      - .pnpm-store
    policy: pull
  variables:
    GIT_LFS_SKIP_SMUDGE: 1
  before_script:
    - ./scripts/ci-install-packages.sh
  script:
    - ./scripts/publish-package.sh assets ${NPM_TOKEN} $CI_COMMIT_TAG

publish-theme-base:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_TAG =~ /^theme-base@/
  image: node:20
  cache:
    key:
      files:
        - pnpm-lock.yaml
      prefix: cache
    paths:
      - .pnpm-store
    policy: pull
  variables:
    GIT_LFS_SKIP_SMUDGE: 1
  before_script:
    - ./scripts/ci-install-packages.sh
  script:
    - ./scripts/publish-package.sh themes/base ${NPM_TOKEN} $CI_COMMIT_TAG

publish-theme-dark:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_TAG =~ /^theme-dark@/
  image: node:20
  cache:
    key:
      files:
        - pnpm-lock.yaml
      prefix: cache
    paths:
      - .pnpm-store
    policy: pull
  variables:
    GIT_LFS_SKIP_SMUDGE: 1
  before_script:
    - ./scripts/ci-install-packages.sh
  script:
    - ./scripts/publish-package.sh themes/dark ${NPM_TOKEN} $CI_COMMIT_TAG

publish-theme-mm:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_TAG =~ /^theme-mm@/
  image: node:20
  cache:
    key:
      files:
        - pnpm-lock.yaml
      prefix: cache
    paths:
      - .pnpm-store
    policy: pull
  variables:
    GIT_LFS_SKIP_SMUDGE: 1
  before_script:
    - ./scripts/ci-install-packages.sh
  script:
    - ./scripts/publish-package.sh themes/message-media ${NPM_TOKEN} $CI_COMMIT_TAG

publish-theme-cpaas-base:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG =~ /^theme-cpaas-base@/
  image: node:20
  cache:
    key:
      files:
        - pnpm-lock.yaml
      prefix: cache
    paths:
      - .pnpm-store
    policy: pull
  variables:
    GIT_LFS_SKIP_SMUDGE: 1
  before_script:
    - ./scripts/ci-install-packages.sh
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    - npm publish themes/cpaas-base/ --verbose
    - node ./scripts/slack-changelog.js themes/cpaas-base

publish-theme-cpaas-dashboard:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG =~ /^theme-cpaas-dashboard@/
  image: node:20
  cache:
    key:
      files:
        - pnpm-lock.yaml
      prefix: cache
    paths:
      - .pnpm-store
    policy: pull
  variables:
    GIT_LFS_SKIP_SMUDGE: 1
  before_script:
    - ./scripts/ci-install-packages.sh
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    - npm publish themes/cpaas-dashboard/ --verbose
    - node ./scripts/slack-changelog.js themes/cpaas-dashboard

publish-theme-cpaas-mailgun:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG =~ /^theme-cpaas-mailgun@/
  image: node:20
  cache:
    key:
      files:
        - pnpm-lock.yaml
      prefix: cache
    paths:
      - .pnpm-store
    policy: pull
  variables:
    GIT_LFS_SKIP_SMUDGE: 1
  before_script:
    - ./scripts/ci-install-packages.sh
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    - npm publish themes/cpaas-mailgun/ --verbose
    - node ./scripts/slack-changelog.js themes/cpaas-mailgun
publish-wrappers-react:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG =~ /^wrappers-react@/
  image: node:20
  cache:
    key:
      files:
        - pnpm-lock.yaml
      prefix: cache
    paths:
      - .pnpm-store
    policy: pull
  variables:
    GIT_LFS_SKIP_SMUDGE: 1
  before_script:
    - ./scripts/ci-install-packages.sh
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    - pnpm --dir wrappers/react build
    - npm publish wrappers/react/ --verbose
    - node ./scripts/slack-changelog.js wrappers/react
publish-theme-cpaas-mailjet:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG =~ /^theme-cpaas-mailjet@/
  image: node:20
  cache:
    key:
      files:
        - pnpm-lock.yaml
      prefix: cache
    paths:
      - .pnpm-store
    policy: pull
  variables:
    GIT_LFS_SKIP_SMUDGE: 1
  before_script:
    - ./scripts/ci-install-packages.sh
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    - npm publish themes/cpaas-mailjet/ --verbose
    - node ./scripts/slack-changelog.js themes/cpaas-mailjet

build-docs:
  stage: build
  image: node:20
  rules:
    - if: $CI_COMMIT_TAG =~ /^components@/
    - if: $CI_COMMIT_TAG == "docs"
  cache:
    key:
      files:
        - pnpm-lock.yaml
      prefix: cache
    paths:
      - .pnpm-store
  variables:
    GIT_LFS_SKIP_SMUDGE: 1
  before_script:
    - npm install --no-audit --no-fund --global pnpm
    - pnpm config set store-dir .pnpm-store
    - pnpm install --frozen-lockfile
    - rm -rf .git/hooks/
  script:
    - git config --global user.email ci@sinch.com
    - git config --global user.name Bot
    - git fetch origin refs/heads/docs
    - git checkout origin/docs -- public
    - ./scripts/generate-docs.sh
    - git branch -D docs || true
    - git checkout --orphan docs
    - git reset
    - git add -f public
    - git commit -m "build docs"
    - git push --force "https://gitlab-ci-token:$PROJECT_ACCESS_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git"
  artifacts:
    paths:
      - public

publish-docs:
  stage: deploy
  image: 652860480992.dkr.ecr.eu-west-1.amazonaws.com/aws-cli-runner
  needs:
    - build-docs
  rules:
    - if: $CI_COMMIT_TAG =~ /^components@/
    - if: $CI_COMMIT_TAG == "docs"
  variables:
    GIT_LFS_SKIP_SMUDGE: 1
  script:
    - appcli use production
    - aws s3 rm s3://${BUCKET_ID}/.public/ --recursive --exclude ""
    - aws s3 cp public/ s3://${BUCKET_ID}/.public/ --recursive --include "*"
    - aws cloudfront create-invalidation --distribution-id ${DISTRIBUTION_ID} --paths "/*"

pages:
  stage: deploy
  image: node:20
  rules:
    - if: $CI_COMMIT_TAG == "preview"
  cache:
    key:
      files:
        - pnpm-lock.yaml
      prefix: cache
    paths:
      - .pnpm-store
  variables:
    GIT_LFS_SKIP_SMUDGE: 1
  before_script:
    - npm install --no-audit --no-fund --global pnpm
    - pnpm config set store-dir .pnpm-store
    - pnpm install --frozen-lockfile
  script:
    - ./scripts/generate-docs.sh
  artifacts:
    paths:
      - public
