apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  namespace: apps
  name: nectary # nectary is a reserved name across Sinch
  description: Nectary design system
spec:
  owner: applications-nectary
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  namespace: apps
  name: nectary-library # nectary is a reserved name across Sinch
  description: The Nectary library implements the Nectary design system
  annotations:
    gitlab.com/project-id: "36072357"
  links:
    - url: https://www.figma.com/file/1jOZ4kiqo1BNWGsmEjsWrR/🐝-Nectary-–-Global-Library?node-id=116%3A2660
      title: Figma
    - url: https://sinch.slack.com/archives/C02P9FTRD99
      title: Support Slack 
spec:
  type: library
  lifecycle: production
  owner: applications-nectary
  system: nectary
