apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: nectary-design-system # nectary is a reserved name across Sinch
  description: Nectary
spec:
  owner: applications-nectary
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: applications-nectary
  description: The Nectary team
spec:
  type: team
  profile:
    displayName: Nectary
  parent: applications-common
  members: [] # TODO: Add this when we know usernames
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: nectary # nectary is a reserved name across Sinch
  description: Nectary design system
spec:
  owner: applications-nectary
  domain: nectary-design-system
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nectary-library # nectary is a reserved name across Sinch
  description: The Nectary library implements the Nectary design system
  annotations:
    - gitlab.com/project-id: 36072357
  links:
    - url: https://www.figma.com/file/1jOZ4kiqo1BNWGsmEjsWrR/🐝-Nectary-–-Global-Library?node-id=116%3A2660
      title: Figma
    - url: https://sinch.slack.com/archives/C02P9FTRD99
      title: Support Slack 
spec:
  type: library
  lifecycle: production
  owner: applications-nectary
---
