packages:
  - 'assets/'
  - 'components/'
  - 'react-components/'
  - 'shared/'
  - 'themes/*'
  - 'libs/*'
  - 'packages/*'
  - 'tests/'
  - 'tests/apps/*'
  - 'docs/*'
  - 'tokens/'
  - 'wrappers/*'
  - 'labs'
