import { Meta, StoryObj } from '@storybook/react';
import { Select, SelectButton, SelectMenu } from './SelectMenu';

declare const meta: Meta<typeof SelectMenu>;
export default meta;
type Story = StoryObj<typeof SelectMenu>;
export declare const Default: Story;
export declare const WithSelectedValue: Story;
export declare const MultipleSelection: Story;
export declare const WithSearch: Story;
export declare const WithRows: Story;
export declare const WithDisabledOptions: Story;
export declare const WithIcons: Story;
export declare const Controlled: Story;
export declare const ButtonDefault: StoryObj<typeof SelectButton>;
export declare const ButtonWithText: StoryObj<typeof SelectButton>;
export declare const ButtonSizes: StoryObj<typeof SelectButton>;
export declare const ButtonStates: StoryObj<typeof SelectButton>;
export declare const ButtonWithIcon: StoryObj<typeof SelectButton>;
export declare const CompoundUsage: StoryObj<typeof Select>;
export declare const FullExample: StoryObj<typeof Select>;
