import fs from "node:fs";
import path from "node:path";
import { JSDOM } from "jsdom";

const dirname = (import.meta as any).dirname as string;
const componentsDir = path.join(dirname, "..", "components");

function getAllComponents(): string[] {
  return fs
    .readdirSync(componentsDir)
    .filter((file) => fs.statSync(path.join(componentsDir, file)).isDirectory())
    .filter(
      (file) =>
        file !== "node_modules" && file !== "utils" && file !== "stop-events",
    );
}

function createSlotMap(components: string[]): Map<string, string[]> {
  const componentSlots = new Map<string, string[]>();
  for (const component: string of components) {
    const htmlContent = fs.readFileSync(
      path.join(componentsDir, component, "template.html"),
    );
    const j = new JSDOM(htmlContent);
    const slots = Array.from(j.window.document.querySelectorAll("slot")).map(
      (slot) => slot.name,
    );
    componentSlots.set(component, slots);
  }
  return componentSlots;
}

enum SlotStyle {
  NoSlots,
  Named,
  Unnamed,
  // An invalid state
  Both,
}

function stringOptionType(s: string[]): string {
  return s.map((x) => `'${x}'`).join(" | ");
}

function typeDeclarationLine(componentName: string, t: string): string {
  return `'sinch-${componentName}': ${t}`;
}

function declareNamedSlots(
  componentName: string,
  slots: string[],
): string | null {
  const slotStyle = getSlotStyle(slots);
  const options =
    slotStyle === SlotStyle.Named ? stringOptionType(slots) : "never";
  return typeDeclarationLine(componentName, options);
}

function declareUnnamedSlot(componentName: string, slots: string[]) {
  const slotStyle = getSlotStyle(slots);
  if (slotStyle === SlotStyle.Both) {
    throw new Error("SlotStyle both not supported");
  }
  const options = slotStyle === SlotStyle.Unnamed ? "1" : "never";
  return typeDeclarationLine(componentName, options);
}

function getSlotStyle(slots: string[]): SlotStyle {
  if (slots.length === 0) {
    return SlotStyle.NoSlots;
  }
  const hasUnnamed = slots.find((x) => x === "") !== undefined;
  const hasNamed = slots.find((x) => x !== "") !== undefined;
  const hasBoth = hasUnnamed && hasNamed;
  if (hasBoth) {
    return SlotStyle.Both;
  }
  if (hasNamed) {
    return SlotStyle.Named;
  }
  if (hasUnnamed) {
    return SlotStyle.Unnamed;
  }
  throw new Error("No such slotstyle");
}

function createSlotsTypes(slotsMap: Map<string, string[]>) {
  const namedSlotTypes = [];
  const unnamedSlotsTypes = [];
  for (const [key, value] of slotsMap.entries()) {
    namedSlotTypes.push(declareNamedSlots(key, value));
    unnamedSlotsTypes.push(declareUnnamedSlot(key, value));
  }

  const unnamedSlotsTypesText = unnamedSlotsTypes.join(",\n");
  const namedSlotsTypesText = namedSlotTypes.join(",\n");

  return `
    // AUTOGENERATED DO NOT EDIT
    export interface UnnamedSlots {
        ${unnamedSlotsTypesText}
    }
    export interface NamedSlots {
        ${namedSlotsTypesText}
    }
  `;
}

function saveSlotsFile(data: string) {
  const fp = path.join(dirname, "..", "wrappers", "react", "src", "slots.ts");
  fs.writeFileSync(fp, data);
}

const components = getAllComponents();
const componentSlots = createSlotMap(components);
const slotTypes = createSlotsTypes(componentSlots);
saveSlotsFile(slotTypes);
