import fs from 'node:fs/promises'
import path from 'node:path'
import { JSDOM } from 'jsdom'

const dirname = (import.meta as any).dirname as string
const componentsDir = path.join(dirname, '..', 'components/src')

const IGNORED_FOLDERS = ['node_modules', 'utils', 'stop-events']

const SlotStyle = {
  NoSlots: 0,
  Named: 1,
  Unnamed: 2,
  // An invalid state
  Both: 3,
} as const

type TSlotStyle = (typeof SlotStyle)[keyof typeof SlotStyle]

function getSlotStyle(slots: string[]): TSlotStyle {
  if (slots.length === 0) {
    return SlotStyle.NoSlots
  }

  const hasUnnamed = slots.find((x) => x === '') !== undefined
  const hasNamed = slots.find((x) => x !== '') !== undefined
  const hasBoth = hasUnnamed && hasNamed

  if (hasBoth) {
    return SlotStyle.Both
  }

  if (hasNamed) {
    return SlotStyle.Named
  }

  if (hasUnnamed) {
    return SlotStyle.Unnamed
  }
  throw new Error('No such slotstyle')
}

async function getAllComponents(): Promise<string[]> {
  const components = []
  const files = await fs.readdir(componentsDir)

  for (const file of files) {
    const stat = await fs.stat(path.join(componentsDir, file))
    const isDir = stat.isDirectory()

    if (isDir && !IGNORED_FOLDERS.includes(file)) {
      components.push(file)
    }
  }

  return components
}

async function createSlotMap(
  components: string[]
): Promise<Map<string, string[]>> {
  const componentSlots = new Map<string, string[]>()

  for (const component of components) {
    const htmlContent = await fs.readFile(
      path.join(componentsDir, component, 'template.html')
    )
    const j = new JSDOM(htmlContent)
    const slots = Array.from(j.window.document.querySelectorAll('slot')).map(
      (slot) => slot.name
    )

    componentSlots.set(component, slots)
  }

  return componentSlots
}

function stringOptionType(s: string[]): string {
  return s.map((x) => `'${x}'`).join(' | ')
}

function typeDeclarationLine(componentName: string, t: string): string {
  return `  'sinch-${componentName}': ${t}`
}

function declareNamedSlots(
  componentName: string,
  slots: string[]
): string | null {
  const slotStyle = getSlotStyle(slots)
  const options =
    slotStyle === SlotStyle.Named ? stringOptionType(slots) : 'never'

  return typeDeclarationLine(componentName, options)
}

function declareUnnamedSlot(componentName: string, slots: string[]) {
  const slotStyle = getSlotStyle(slots)

  if (slotStyle === SlotStyle.Both) {
    throw new Error('SlotStyle both not supported')
  }

  const options = slotStyle === SlotStyle.Unnamed ? '1' : 'never'

  return typeDeclarationLine(componentName, options)
}

function createSlotsTypes(slotsMap: Map<string, string[]>) {
  const namedSlotTypes = []
  const unnamedSlotsTypes = []

  for (const [key, value] of slotsMap.entries()) {
    namedSlotTypes.push(declareNamedSlots(key, value))
    unnamedSlotsTypes.push(declareUnnamedSlot(key, value))
  }

  const unnamedSlotsTypesText = unnamedSlotsTypes.join(',\n')
  const namedSlotsTypesText = namedSlotTypes.join(',\n')

  return `
    // AUTOGENERATED DO NOT EDIT
    export interface UnnamedSlots {
    ${unnamedSlotsTypesText}
    }
    export interface NamedSlots {
    ${namedSlotsTypesText}
    }
  `
}

async function saveSlotsFile(data: string) {
  const fp = path.join(dirname, '..', 'wrappers', 'react', 'src', 'slots.ts')

  await fs.writeFile(fp, data)
}

const components = await getAllComponents()
const componentSlots = await createSlotMap(components)
const slotTypes = createSlotsTypes(componentSlots)

await saveSlotsFile(slotTypes)
