#!/bin/bash

cd "$(dirname "$0")"

# Define the output file
output_file="../components/standalone.ts"
output_file="$(cd "$(dirname "$output_file")"; pwd)/$(basename "$output_file")"

# Write the static content to the file
cat <<EOT > "$output_file"
// Standalone file with all Nectary components installed into window
// AUTOGENERATED: DO NOT EDIT
/* eslint-disable import/first */
import { setNectaryRegistry } from './utils';
setNectaryRegistry(window.customElements);

// Reminder: Keep this list updated as we add new components
EOT

cd ../components/

# Append dynamic import statements for each subdirectory
for dir in */ ; do
    if [ -d "$dir" ]; then
        echo "import './${dir%/}'" >> "$output_file"
    fi
done

echo "Generated $output_file with all component imports."
